name: CVE Container Scanning
on: [push]
jobs:
  Aqua-Trivy-Scan:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/datawire/aes:2.3.2'
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
  Grype-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan image
        id: scan
        uses: anchore/scan-action@v3
        with:
          image: "docker.io/datawire/aes:2.3.2"
          acs-report-enable: true
          fail-build: false
      - name: Upload scan results to Github
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file:  ${{ steps.scan.outputs.sarif }}


