name: CVE Container Scanning
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.build-image.outputs.image-tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build-image
        id: build-image
        shell: bash
        run: |
          ls docker
          echo "::set-output name=image-tag::$$(echo $(sed -n 2p docker/emissary.docker.tag.remote))"

  Aqua-Trivy-Scan:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: What is my tag
        shell: bash
        run: echo ${{needs.build.outputs.image-tag}}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{needs.build.outputs.image-tag}}
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
  Grype-Scan:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Scan image
        id: scan
        uses: anchore/scan-action@v3
        with:
          image: ${{needs.build.outputs.image-tag}}
          acs-report-enable: true
          fail-build: false
      - name: Upload scan results to Github
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file:  ${{ steps.scan.outputs.sarif }}


